// 業務目線のツリー構造データ

export type NodeType = 'department' | 'category' | 'kpi' | 'decision';

export type KPIStatus = 'good' | 'warning' | 'critical' | 'neutral';

export interface TreeNode {
  id: string;
  name: string;
  type: NodeType;
  icon?: string;
  description?: string;
  children?: TreeNode[];
  // KPIノード用
  kpiValue?: string | number;
  kpiUnit?: string;
  kpiTarget?: string | number;
  kpiStatus?: KPIStatus;
  kpiTrend?: 'up' | 'down' | 'stable';
  // 意思決定ノード用
  decisionId?: string;
  urgency?: 'immediate' | 'this_week' | 'this_month' | 'this_quarter';
  deadline?: string;
}

export interface DepartmentSummary {
  id: string;
  name: string;
  icon: string;
  description: string;
  kpiCount: number;
  decisionCount: number;
  alertCount: number;
  goodCount: number;
}

// 部門サマリーデータ
export const departmentSummaries: DepartmentSummary[] = [
  {
    id: 'management',
    name: '経営企画',
    icon: '📊',
    description: '全社業績・戦略・予算管理',
    kpiCount: 12,
    decisionCount: 2,
    alertCount: 1,
    goodCount: 8,
  },
  {
    id: 'sales',
    name: '営業',
    icon: '💼',
    description: '受注・商談・顧客管理',
    kpiCount: 15,
    decisionCount: 1,
    alertCount: 2,
    goodCount: 10,
  },
  {
    id: 'hr',
    name: '人事',
    icon: '👥',
    description: '採用・育成・評価・労務',
    kpiCount: 10,
    decisionCount: 1,
    alertCount: 0,
    goodCount: 7,
  },
  {
    id: 'finance',
    name: '財務・経理',
    icon: '💰',
    description: '資金繰り・投資・コスト管理',
    kpiCount: 8,
    decisionCount: 1,
    alertCount: 1,
    goodCount: 5,
  },
  {
    id: 'operations',
    name: '事業部',
    icon: '🏢',
    description: 'プロジェクト・支社別業績',
    kpiCount: 20,
    decisionCount: 2,
    alertCount: 3,
    goodCount: 12,
  },
  {
    id: 'tech',
    name: '技術・開発',
    icon: '💻',
    description: '開発進捗・品質・技術投資',
    kpiCount: 8,
    decisionCount: 0,
    alertCount: 1,
    goodCount: 5,
  },
];

// ツリー構造データ
export const businessTree: TreeNode[] = [
  {
    id: 'management',
    name: '経営企画',
    type: 'department',
    icon: '📊',
    description: '全社業績・戦略・予算管理',
    children: [
      {
        id: 'mgmt-revenue',
        name: '売上・収益',
        type: 'category',
        children: [
          {
            id: 'kpi-total-revenue',
            name: '売上高',
            type: 'kpi',
            kpiValue: 92.5,
            kpiUnit: '億円',
            kpiTarget: 100,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-revenue-growth',
            name: '売上成長率',
            type: 'kpi',
            kpiValue: 5.1,
            kpiUnit: '%',
            kpiTarget: 8,
            kpiStatus: 'warning',
            kpiTrend: 'stable',
          },
          {
            id: 'dec-revenue-target',
            name: '下期売上目標の修正',
            type: 'decision',
            decisionId: 'dec-001',
            urgency: 'this_week',
            deadline: '2025-10-15',
            description: '上期実績を踏まえた下期目標の見直し',
          },
        ],
      },
      {
        id: 'mgmt-profit',
        name: '利益管理',
        type: 'category',
        children: [
          {
            id: 'kpi-gross-profit',
            name: '粗利益',
            type: 'kpi',
            kpiValue: 13.5,
            kpiUnit: '億円',
            kpiTarget: 15,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-margin-rate',
            name: '粗利率',
            type: 'kpi',
            kpiValue: 14.6,
            kpiUnit: '%',
            kpiTarget: 15,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-operating-profit',
            name: '営業利益',
            type: 'kpi',
            kpiValue: 5.2,
            kpiUnit: '億円',
            kpiTarget: 6,
            kpiStatus: 'warning',
            kpiTrend: 'stable',
          },
        ],
      },
      {
        id: 'mgmt-budget',
        name: '予算管理',
        type: 'category',
        children: [
          {
            id: 'kpi-budget-achievement',
            name: '予算達成率',
            type: 'kpi',
            kpiValue: 92.5,
            kpiUnit: '%',
            kpiTarget: 100,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-cost-variance',
            name: 'コスト差異',
            type: 'kpi',
            kpiValue: -2.3,
            kpiUnit: '%',
            kpiTarget: 0,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
        ],
      },
    ],
  },
  {
    id: 'sales',
    name: '営業',
    type: 'department',
    icon: '💼',
    description: '受注・商談・顧客管理',
    children: [
      {
        id: 'sales-orders',
        name: '受注・商談',
        type: 'category',
        children: [
          {
            id: 'kpi-orders',
            name: '受注金額',
            type: 'kpi',
            kpiValue: 45.2,
            kpiUnit: '億円',
            kpiTarget: 50,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-deals',
            name: '商談数',
            type: 'kpi',
            kpiValue: 156,
            kpiUnit: '件',
            kpiTarget: 180,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-win-rate',
            name: '成約率',
            type: 'kpi',
            kpiValue: 32,
            kpiUnit: '%',
            kpiTarget: 35,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
        ],
      },
      {
        id: 'sales-pipeline',
        name: 'パイプライン',
        type: 'category',
        children: [
          {
            id: 'kpi-pipeline',
            name: 'パイプライン総額',
            type: 'kpi',
            kpiValue: 115,
            kpiUnit: '億円',
            kpiTarget: 120,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-carryover',
            name: '繰越案件',
            type: 'kpi',
            kpiValue: 63.5,
            kpiUnit: '億円',
            kpiTarget: 60,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
        ],
      },
      {
        id: 'sales-team',
        name: '営業体制',
        type: 'category',
        children: [
          {
            id: 'kpi-sales-headcount',
            name: '営業人員',
            type: 'kpi',
            kpiValue: 42,
            kpiUnit: '名',
            kpiTarget: 50,
            kpiStatus: 'critical',
            kpiTrend: 'stable',
          },
          {
            id: 'kpi-productivity',
            name: '人員あたり売上',
            type: 'kpi',
            kpiValue: 2.2,
            kpiUnit: '億円',
            kpiTarget: 2.0,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'dec-sales-hiring',
            name: '営業人員の増強',
            type: 'decision',
            decisionId: 'dec-002',
            urgency: 'this_month',
            deadline: '2025-10-31',
            description: '下期の売上目標達成に向けた営業人員の採用判断',
          },
        ],
      },
    ],
  },
  {
    id: 'hr',
    name: '人事',
    type: 'department',
    icon: '👥',
    description: '採用・育成・評価・労務',
    children: [
      {
        id: 'hr-recruitment',
        name: '採用',
        type: 'category',
        children: [
          {
            id: 'kpi-new-hires',
            name: '新規採用数',
            type: 'kpi',
            kpiValue: 15,
            kpiUnit: '名',
            kpiTarget: 20,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-hiring-cost',
            name: '採用単価',
            type: 'kpi',
            kpiValue: 85,
            kpiUnit: '万円',
            kpiTarget: 100,
            kpiStatus: 'good',
            kpiTrend: 'down',
          },
          {
            id: 'kpi-offer-rate',
            name: '内定承諾率',
            type: 'kpi',
            kpiValue: 78,
            kpiUnit: '%',
            kpiTarget: 80,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
        ],
      },
      {
        id: 'hr-retention',
        name: '定着・離職',
        type: 'category',
        children: [
          {
            id: 'kpi-turnover',
            name: '離職率',
            type: 'kpi',
            kpiValue: 8.5,
            kpiUnit: '%',
            kpiTarget: 10,
            kpiStatus: 'good',
            kpiTrend: 'down',
          },
          {
            id: 'kpi-retention',
            name: '定着率（1年）',
            type: 'kpi',
            kpiValue: 92,
            kpiUnit: '%',
            kpiTarget: 90,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
        ],
      },
      {
        id: 'hr-development',
        name: '育成・評価',
        type: 'category',
        children: [
          {
            id: 'kpi-training-hours',
            name: '研修時間',
            type: 'kpi',
            kpiValue: 24,
            kpiUnit: '時間/人',
            kpiTarget: 30,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-promotion-rate',
            name: '昇進率',
            type: 'kpi',
            kpiValue: 12,
            kpiUnit: '%',
            kpiTarget: 15,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
        ],
      },
    ],
  },
  {
    id: 'finance',
    name: '財務・経理',
    type: 'department',
    icon: '💰',
    description: '資金繰り・投資・コスト管理',
    children: [
      {
        id: 'fin-cashflow',
        name: '資金繰り',
        type: 'category',
        children: [
          {
            id: 'kpi-cash-balance',
            name: '現預金残高',
            type: 'kpi',
            kpiValue: 25.3,
            kpiUnit: '億円',
            kpiTarget: 20,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-operating-cf',
            name: '営業キャッシュフロー',
            type: 'kpi',
            kpiValue: 4.2,
            kpiUnit: '億円',
            kpiTarget: 5,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
        ],
      },
      {
        id: 'fin-investment',
        name: '投資',
        type: 'category',
        children: [
          {
            id: 'kpi-capex',
            name: '設備投資額',
            type: 'kpi',
            kpiValue: 3.5,
            kpiUnit: '億円',
            kpiTarget: 5,
            kpiStatus: 'neutral',
            kpiTrend: 'stable',
          },
          {
            id: 'kpi-rd-investment',
            name: 'R&D投資',
            type: 'kpi',
            kpiValue: 2.1,
            kpiUnit: '億円',
            kpiTarget: 2.5,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'dec-investment-plan',
            name: '来期の投資計画',
            type: 'decision',
            decisionId: 'dec-005',
            urgency: 'this_quarter',
            deadline: '2025-12-20',
            description: '来期の設備投資・R&D投資の優先順位決定',
          },
        ],
      },
      {
        id: 'fin-cost',
        name: 'コスト管理',
        type: 'category',
        children: [
          {
            id: 'kpi-sg-a',
            name: '販管費率',
            type: 'kpi',
            kpiValue: 18.5,
            kpiUnit: '%',
            kpiTarget: 20,
            kpiStatus: 'good',
            kpiTrend: 'down',
          },
          {
            id: 'kpi-labor-cost',
            name: '人件費率',
            type: 'kpi',
            kpiValue: 42,
            kpiUnit: '%',
            kpiTarget: 45,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
        ],
      },
    ],
  },
  {
    id: 'operations',
    name: '事業部',
    type: 'department',
    icon: '🏢',
    description: 'プロジェクト・支社別業績',
    children: [
      {
        id: 'ops-projects',
        name: 'プロジェクト管理',
        type: 'category',
        children: [
          {
            id: 'kpi-project-count',
            name: '稼働プロジェクト',
            type: 'kpi',
            kpiValue: 120,
            kpiUnit: '件',
            kpiTarget: 100,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-project-margin',
            name: 'プロジェクト平均粗利率',
            type: 'kpi',
            kpiValue: 12.2,
            kpiUnit: '%',
            kpiTarget: 15,
            kpiStatus: 'warning',
            kpiTrend: 'stable',
          },
          {
            id: 'kpi-red-projects',
            name: '赤字プロジェクト',
            type: 'kpi',
            kpiValue: 3,
            kpiUnit: '件',
            kpiTarget: 0,
            kpiStatus: 'critical',
            kpiTrend: 'stable',
          },
          {
            id: 'dec-red-project',
            name: '赤字プロジェクトの継続判断',
            type: 'decision',
            decisionId: 'dec-004',
            urgency: 'this_week',
            deadline: '2025-10-10',
            description: '大幅な赤字が見込まれるプロジェクトの継続可否',
          },
        ],
      },
      {
        id: 'ops-branch',
        name: '支社別業績',
        type: 'category',
        children: [
          {
            id: 'kpi-tokyo',
            name: '東京本社',
            type: 'kpi',
            kpiValue: 14.9,
            kpiUnit: '% 粗利率',
            kpiTarget: 15,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-osaka',
            name: '大阪支社',
            type: 'kpi',
            kpiValue: 13.6,
            kpiUnit: '% 粗利率',
            kpiTarget: 14,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-nagoya',
            name: '名古屋支社',
            type: 'kpi',
            kpiValue: 12.6,
            kpiUnit: '% 粗利率',
            kpiTarget: 13,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
          {
            id: 'kpi-tohoku',
            name: '東北支社',
            type: 'kpi',
            kpiValue: 5.2,
            kpiUnit: '% 粗利率',
            kpiTarget: 12,
            kpiStatus: 'critical',
            kpiTrend: 'down',
          },
          {
            id: 'dec-tohoku-margin',
            name: '東北支社の粗利率改善',
            type: 'decision',
            decisionId: 'dec-003',
            urgency: 'immediate',
            deadline: '2025-10-05',
            description: '粗利率5.2%と低迷する東北支社の収益性改善施策',
          },
        ],
      },
      {
        id: 'ops-segment',
        name: '事業セグメント',
        type: 'category',
        children: [
          {
            id: 'kpi-saas',
            name: 'SaaS事業',
            type: 'kpi',
            kpiValue: 33.1,
            kpiUnit: '億円',
            kpiTarget: 35,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-aiml',
            name: 'AI/ML事業',
            type: 'kpi',
            kpiValue: 23.1,
            kpiUnit: '億円',
            kpiTarget: 25,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-cloud',
            name: 'クラウド事業',
            type: 'kpi',
            kpiValue: 17.0,
            kpiUnit: '億円',
            kpiTarget: 18,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
        ],
      },
    ],
  },
  {
    id: 'tech',
    name: '技術・開発',
    type: 'department',
    icon: '💻',
    description: '開発進捗・品質・技術投資',
    children: [
      {
        id: 'tech-delivery',
        name: '開発デリバリー',
        type: 'category',
        children: [
          {
            id: 'kpi-delivery-rate',
            name: '納期遵守率',
            type: 'kpi',
            kpiValue: 94,
            kpiUnit: '%',
            kpiTarget: 95,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-bug-rate',
            name: '障害発生率',
            type: 'kpi',
            kpiValue: 2.1,
            kpiUnit: '%',
            kpiTarget: 3,
            kpiStatus: 'good',
            kpiTrend: 'down',
          },
        ],
      },
      {
        id: 'tech-quality',
        name: '品質管理',
        type: 'category',
        children: [
          {
            id: 'kpi-test-coverage',
            name: 'テストカバレッジ',
            type: 'kpi',
            kpiValue: 78,
            kpiUnit: '%',
            kpiTarget: 80,
            kpiStatus: 'good',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-tech-debt',
            name: '技術負債指数',
            type: 'kpi',
            kpiValue: 3.2,
            kpiUnit: '',
            kpiTarget: 3,
            kpiStatus: 'warning',
            kpiTrend: 'stable',
          },
        ],
      },
      {
        id: 'tech-resource',
        name: '技術リソース',
        type: 'category',
        children: [
          {
            id: 'kpi-engineer-count',
            name: 'エンジニア数',
            type: 'kpi',
            kpiValue: 85,
            kpiUnit: '名',
            kpiTarget: 90,
            kpiStatus: 'warning',
            kpiTrend: 'up',
          },
          {
            id: 'kpi-utilization',
            name: '稼働率',
            type: 'kpi',
            kpiValue: 82,
            kpiUnit: '%',
            kpiTarget: 85,
            kpiStatus: 'good',
            kpiTrend: 'stable',
          },
        ],
      },
    ],
  },
];

// 緊急度のラベルと色
export const urgencyConfig = {
  immediate: { label: '緊急', color: 'bg-red-100 text-red-800 border-red-200' },
  this_week: { label: '今週中', color: 'bg-orange-100 text-orange-800 border-orange-200' },
  this_month: { label: '今月中', color: 'bg-yellow-100 text-yellow-800 border-yellow-200' },
  this_quarter: { label: '今四半期', color: 'bg-blue-100 text-blue-800 border-blue-200' },
};

// KPIステータスの色
export const kpiStatusConfig = {
  good: { color: 'text-emerald-600', bg: 'bg-emerald-50', icon: '●' },
  warning: { color: 'text-amber-600', bg: 'bg-amber-50', icon: '●' },
  critical: { color: 'text-red-600', bg: 'bg-red-50', icon: '●' },
  neutral: { color: 'text-slate-600', bg: 'bg-slate-50', icon: '●' },
};
