import { DecisionBox } from './types';

/**
 * 意思決定ボックスのデモデータ
 * 経営判断に必要な典型的な意思決定シナリオ
 */
export const DEMO_DECISIONS: DecisionBox[] = [
  {
    id: 'dec-001',
    title: '下期売上目標の修正',
    purpose: '上期実績を踏まえ、下期の売上目標を現実的な水準に修正すべきか判断する',
    category: 'financial',
    urgency: 'this_week',
    status: 'in_review',
    owner: '代表取締役',
    stakeholders: ['営業本部長', '経理部長', '各支社長'],
    inputs: [
      {
        id: 'inp-001',
        label: '上期売上実績',
        value: 89.2,
        unit: '億円',
        trend: 'down',
        source: '経理システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-002',
        label: '上期目標達成率',
        value: 94.5,
        unit: '%',
        trend: 'down',
        source: '経理システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-003',
        label: '受注残高',
        value: 45.3,
        unit: '億円',
        trend: 'stable',
        source: '営業システム',
        updatedAt: '2025-09-30',
      },
      {
        id: 'inp-004',
        label: '商談パイプライン',
        value: 62.1,
        unit: '億円',
        trend: 'up',
        source: 'CRM',
        updatedAt: '2025-09-28',
      },
    ],
    constraints: [
      {
        id: 'con-001',
        description: '株主総会で発表した年間目標（190億円）との整合性',
        type: 'hard',
        impact: 'high',
      },
      {
        id: 'con-002',
        description: '従業員の賞与原資への影響',
        type: 'soft',
        impact: 'medium',
      },
      {
        id: 'con-003',
        description: '来期予算策定への影響',
        type: 'soft',
        impact: 'medium',
      },
    ],
    options: [
      {
        id: 'opt-001',
        label: '目標維持（190億円）',
        description: '当初目標を維持し、下期に巻き返しを図る',
        pros: ['株主への説明不要', '従業員のモチベーション維持'],
        cons: ['未達リスク大', '無理な営業活動による品質低下'],
        estimatedImpact: {
          revenue: 19000000000,
          risk: 'high',
          timeframe: '2025年度末',
        },
        recommendationScore: 35,
      },
      {
        id: 'opt-002',
        label: '目標修正（180億円）',
        description: '現実的な水準に5%下方修正',
        pros: ['達成可能性向上', '適切なリソース配分が可能'],
        cons: ['株主への説明が必要', '一部従業員の士気低下'],
        estimatedImpact: {
          revenue: 18000000000,
          risk: 'medium',
          timeframe: '2025年度末',
        },
        recommendationScore: 75,
        isRecommended: true,
      },
      {
        id: 'opt-003',
        label: '目標大幅修正（170億円）',
        description: '保守的に10%下方修正',
        pros: ['高い達成確度', '来期への布石'],
        cons: ['市場からの評価低下', '成長ストーリーの崩壊'],
        estimatedImpact: {
          revenue: 17000000000,
          risk: 'low',
          timeframe: '2025年度末',
        },
        recommendationScore: 45,
      },
    ],
    relatedDecisions: [
      {
        id: 'dec-002',
        title: '営業人員の増強',
        relationship: 'related',
        status: 'pending',
      },
      {
        id: 'dec-004',
        title: '赤字プロジェクトの継続判断',
        relationship: 'related',
        status: 'in_review',
      },
    ],
    deadline: '2025-10-15',
    meetingDate: '2025-10-10',
    createdAt: '2025-09-25',
    updatedAt: '2025-10-01',
    tags: ['財務', '目標管理', 'Q3'],
  },
  {
    id: 'dec-002',
    title: '営業人員の増強',
    purpose: '下期の売上目標達成に向けて、営業人員を増強すべきか判断する',
    category: 'hr',
    urgency: 'this_month',
    status: 'pending',
    owner: '営業本部長',
    stakeholders: ['人事部長', '経理部長', '各支社長'],
    inputs: [
      {
        id: 'inp-010',
        label: '現在の営業人員',
        value: 45,
        unit: '名',
        trend: 'stable',
        source: '人事システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-011',
        label: '営業1人あたり売上',
        value: 1.98,
        unit: '億円/年',
        trend: 'down',
        source: '経理システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-012',
        label: '採用市場の状況',
        value: '売り手市場',
        source: '人事部調査',
        updatedAt: '2025-09-15',
      },
    ],
    constraints: [
      {
        id: 'con-010',
        description: '今期の人件費予算残高（3,000万円）',
        type: 'hard',
        impact: 'high',
      },
      {
        id: 'con-011',
        description: '新人の戦力化に6ヶ月必要',
        type: 'hard',
        impact: 'high',
      },
    ],
    options: [
      {
        id: 'opt-010',
        label: '新規採用（3名）',
        description: '正社員として3名を新規採用',
        pros: ['長期的な戦力', '組織の活性化'],
        cons: ['即戦力にならない', 'コスト高'],
        estimatedImpact: {
          cost: 18000000,
          risk: 'medium',
          timeframe: '6ヶ月',
        },
        recommendationScore: 50,
      },
      {
        id: 'opt-011',
        label: '派遣・業務委託の活用',
        description: '即戦力として派遣営業を3名活用',
        pros: ['即戦力', '柔軟なコスト管理'],
        cons: ['ノウハウが残らない', '帰属意識低い'],
        estimatedImpact: {
          cost: 15000000,
          risk: 'low',
          timeframe: '1ヶ月',
        },
        recommendationScore: 70,
        isRecommended: true,
      },
      {
        id: 'opt-012',
        label: '増員見送り',
        description: '既存メンバーの生産性向上で対応',
        pros: ['コスト抑制', '既存メンバーの成長機会'],
        cons: ['オーバーワークリスク', '目標未達リスク'],
        estimatedImpact: {
          cost: 0,
          risk: 'high',
          timeframe: '-',
        },
        recommendationScore: 30,
      },
    ],
    relatedDecisions: [
      {
        id: 'dec-001',
        title: '下期売上目標の修正',
        relationship: 'blocked_by',
        status: 'in_review',
      },
    ],
    deadline: '2025-10-31',
    createdAt: '2025-09-28',
    updatedAt: '2025-10-01',
    tags: ['人事', '営業', 'リソース'],
  },
  {
    id: 'dec-003',
    title: '東北支社の粗利率改善',
    purpose: '粗利率5.2%と低迷する東北支社の収益性を改善するための施策を決定する',
    category: 'operational',
    urgency: 'immediate',
    status: 'escalated',
    owner: '東北支社長',
    stakeholders: ['営業本部長', '品質管理部長', 'PMO'],
    inputs: [
      {
        id: 'inp-020',
        label: '東北支社粗利率',
        value: 5.2,
        unit: '%',
        trend: 'down',
        source: '経理システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-021',
        label: '全社平均粗利率',
        value: 12.8,
        unit: '%',
        trend: 'stable',
        source: '経理システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-022',
        label: '問題プロジェクト数',
        value: 3,
        unit: '件',
        trend: 'up',
        source: 'PMO報告',
        updatedAt: '2025-09-28',
      },
      {
        id: 'inp-023',
        label: '追加コスト発生額',
        value: 4500,
        unit: '万円',
        trend: 'up',
        source: 'プロジェクト管理システム',
        updatedAt: '2025-09-30',
      },
    ],
    constraints: [
      {
        id: 'con-020',
        description: '顧客との契約条件（追加費用請求不可）',
        type: 'hard',
        impact: 'high',
      },
      {
        id: 'con-021',
        description: '担当SEの離職リスク',
        type: 'soft',
        impact: 'high',
      },
    ],
    options: [
      {
        id: 'opt-020',
        label: '本社からの支援チーム派遣',
        description: 'シニアPMと技術者3名を1ヶ月派遣',
        pros: ['即座に品質改善', 'ノウハウ移転'],
        cons: ['本社リソースの圧迫', '一時的な対処'],
        estimatedImpact: {
          cost: 8000000,
          risk: 'low',
          timeframe: '1ヶ月',
        },
        recommendationScore: 80,
        isRecommended: true,
      },
      {
        id: 'opt-021',
        label: 'プロジェクトの縮小',
        description: 'スコープを縮小し、損失を最小化',
        pros: ['損失拡大防止', 'リソース解放'],
        cons: ['顧客関係悪化', 'レピュテーションリスク'],
        estimatedImpact: {
          cost: 0,
          risk: 'medium',
          timeframe: '2週間',
        },
        recommendationScore: 45,
      },
    ],
    relatedDecisions: [
      {
        id: 'dec-004',
        title: '赤字プロジェクトの継続判断',
        relationship: 'triggers',
        status: 'in_review',
      },
    ],
    deadline: '2025-10-05',
    meetingDate: '2025-10-03',
    createdAt: '2025-09-20',
    updatedAt: '2025-10-01',
    tags: ['支社', '収益性', '緊急'],
  },
  {
    id: 'dec-004',
    title: '赤字プロジェクトの継続判断',
    purpose: '累積赤字が拡大しているプロジェクトXを継続するか、撤退するかを判断する',
    category: 'project',
    urgency: 'this_week',
    status: 'in_review',
    owner: 'PMO責任者',
    stakeholders: ['東北支社長', '営業本部長', '品質管理部長', '法務部長'],
    inputs: [
      {
        id: 'inp-030',
        label: '累積赤字額',
        value: 2800,
        unit: '万円',
        trend: 'up',
        source: 'プロジェクト管理システム',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-031',
        label: 'プロジェクト進捗',
        value: 65,
        unit: '%',
        trend: 'stable',
        source: 'PMO報告',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-032',
        label: '完了までの追加コスト見込み',
        value: 1500,
        unit: '万円',
        source: 'PM見積',
        updatedAt: '2025-09-28',
      },
      {
        id: 'inp-033',
        label: '顧客満足度',
        value: 2.5,
        unit: '/5',
        trend: 'down',
        source: '営業ヒアリング',
        updatedAt: '2025-09-25',
      },
    ],
    constraints: [
      {
        id: 'con-030',
        description: '契約上の義務（中途解約の違約金条項）',
        type: 'hard',
        impact: 'high',
      },
      {
        id: 'con-031',
        description: '顧客は上場企業（レピュテーションリスク）',
        type: 'soft',
        impact: 'high',
      },
      {
        id: 'con-032',
        description: 'チームメンバーのモチベーション',
        type: 'soft',
        impact: 'medium',
      },
    ],
    options: [
      {
        id: 'opt-030',
        label: '継続（体制強化）',
        description: '追加リソースを投入して完遂を目指す',
        pros: ['顧客関係維持', '契約履行', 'チームの経験'],
        cons: ['さらなる損失リスク', 'リソース拘束'],
        estimatedImpact: {
          cost: 15000000,
          risk: 'medium',
          timeframe: '3ヶ月',
        },
        recommendationScore: 55,
      },
      {
        id: 'opt-031',
        label: '継続（現状維持）',
        description: '現在の体制のまま継続',
        pros: ['追加コスト抑制'],
        cons: ['品質リスク大', '納期遅延リスク'],
        estimatedImpact: {
          cost: 0,
          risk: 'high',
          timeframe: '4ヶ月',
        },
        recommendationScore: 25,
      },
      {
        id: 'opt-032',
        label: '顧客との再交渉',
        description: 'スコープ・スケジュールの見直しを提案',
        pros: ['損失最小化', '顧客との協力関係構築'],
        cons: ['交渉難航リスク', '追加要求リスク'],
        estimatedImpact: {
          cost: 5000000,
          risk: 'medium',
          timeframe: '2ヶ月',
        },
        recommendationScore: 70,
        isRecommended: true,
      },
    ],
    relatedDecisions: [
      {
        id: 'dec-001',
        title: '下期売上目標の修正',
        relationship: 'related',
        status: 'in_review',
      },
      {
        id: 'dec-003',
        title: '東北支社の粗利率改善',
        relationship: 'blocked_by',
        status: 'escalated',
      },
    ],
    deadline: '2025-10-08',
    meetingDate: '2025-10-07',
    createdAt: '2025-09-22',
    updatedAt: '2025-10-01',
    tags: ['プロジェクト', 'リスク', '東北支社'],
  },
  {
    id: 'dec-005',
    title: '来期の投資計画',
    purpose: '来期の設備投資・人材投資の優先順位と予算配分を決定する',
    category: 'strategic',
    urgency: 'this_quarter',
    status: 'pending',
    owner: '代表取締役',
    stakeholders: ['CFO', 'CTO', '人事部長', '各本部長'],
    inputs: [
      {
        id: 'inp-040',
        label: '投資可能枠',
        value: 5,
        unit: '億円',
        source: '経理部試算',
        updatedAt: '2025-09-30',
        isKey: true,
      },
      {
        id: 'inp-041',
        label: '設備老朽化率',
        value: 35,
        unit: '%',
        trend: 'up',
        source: '総務部報告',
        updatedAt: '2025-09-15',
      },
      {
        id: 'inp-042',
        label: '競合他社の投資動向',
        value: 'AI投資加速',
        source: '経営企画調査',
        updatedAt: '2025-09-20',
      },
    ],
    constraints: [
      {
        id: 'con-040',
        description: '自己資本比率40%以上の維持',
        type: 'hard',
        impact: 'high',
      },
      {
        id: 'con-041',
        description: '株主還元（配当）との両立',
        type: 'hard',
        impact: 'high',
      },
    ],
    options: [
      {
        id: 'opt-040',
        label: '人材投資重視',
        description: '採用・研修に3億円、設備に2億円',
        pros: ['長期的な競争力強化', '組織能力向上'],
        cons: ['即効性なし', '離職リスク'],
        estimatedImpact: {
          cost: 500000000,
          revenue: 200000000,
          risk: 'medium',
          timeframe: '2-3年',
        },
        recommendationScore: 65,
      },
      {
        id: 'opt-041',
        label: 'DX投資重視',
        description: 'AI・自動化に3億円、人材に2億円',
        pros: ['業務効率化', '競合対抗'],
        cons: ['導入リスク', '現場の抵抗'],
        estimatedImpact: {
          cost: 500000000,
          revenue: 300000000,
          risk: 'medium',
          timeframe: '1-2年',
        },
        recommendationScore: 70,
        isRecommended: true,
      },
      {
        id: 'opt-042',
        label: 'バランス型',
        description: '各領域に均等配分',
        pros: ['リスク分散', '全方位改善'],
        cons: ['インパクト限定的', '中途半端'],
        estimatedImpact: {
          cost: 500000000,
          revenue: 150000000,
          risk: 'low',
          timeframe: '1-3年',
        },
        recommendationScore: 50,
      },
    ],
    relatedDecisions: [
      {
        id: 'dec-001',
        title: '下期売上目標の修正',
        relationship: 'related',
        status: 'in_review',
      },
    ],
    deadline: '2025-12-15',
    meetingDate: '2025-11-20',
    createdAt: '2025-09-01',
    updatedAt: '2025-10-01',
    tags: ['戦略', '投資', '来期計画'],
  },
];

// ユーティリティ関数
export function getDecisionsByUrgency(decisions: DecisionBox[], urgency: DecisionBox['urgency']) {
  return decisions.filter(d => d.urgency === urgency);
}

export function getDecisionsByStatus(decisions: DecisionBox[], status: DecisionBox['status']) {
  return decisions.filter(d => d.status === status);
}

export function getDecisionsByCategory(decisions: DecisionBox[], category: DecisionBox['category']) {
  return decisions.filter(d => d.category === category);
}

export function getRelatedDecisions(decisions: DecisionBox[], decisionId: string): DecisionBox[] {
  const decision = decisions.find(d => d.id === decisionId);
  if (!decision) return [];

  const relatedIds = decision.relatedDecisions.map(r => r.id);
  return decisions.filter(d => relatedIds.includes(d.id));
}
